docker run -d -e CX_APIKEY=$(secrets.AST_API_KEY) \
  -v $(pwd):/home/ubuntu checkmarx/dast:latest web  \
  --base-url=https://deu.ast.checkmarx.net \
  --environment-id=e1cc0999-a525-489f-9f5e-0ddb3236fcac \
  --config=/home/ubuntu/test_config.yaml \
  --output=/home/ubuntu/output \
  --timeout=86400 \
  --update-interval=30 \
  --jvm-properties=-Xmx3G \
  --log-level=debug \
  --verbose \
  --retry=3 \
  --retry-delay=20 2>&1 | tee DAST_dockerimage.log
